# Generated by Django 4.2.6 on 2023-10-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stores",
                to="visits.store",
                verbose_name="Maгазины",
            ),
        ),
    ]
